### ISSUE TITLE
Ordering of pushdown operations

### ISSUE THREAD

**Issue by emanuel1025** [open-infrastructure-labs/caerus#6]
Hi,

We were experimenting with the caerus-dike repository and had a couple of questions:

1) For the below code: 

    `val flineitem = lineitem.filter($"l_shipdate" >= "1994-01-01" && $"l_shipdate" < "1995-01-01").groupBy($"l_partkey", 
    $"l_suppkey").agg((sum($"l_quantity") * 0.5).as("sum_quantity"))`

   How does the pushdown operation work if ONLY aggregate pushdown is enabled?
   For example in [Q20.scala](https://github.com/open-infrastructure-labs/caerus-tpch-spark/blob/1585cd1d42623fd73e62e7d97d438584320196d6/src/main/scala/Q20.scala#L25) (code present above), the aggregate operation is present after a filter. How would the pushdown happen in such a case? (Since the filter operation is not pushed down, does the aggregate pushdown get executed since it is not the first operation seen?)

2) To generalize from the first point, do certain enabled pushdown operations get excluded because they do not appear at the beginning of the list of data transformations? 

Thanks,
Prajeeth

**Comment by rfoley-fw** [comment]
Hi Prajeeth,
Thanks for the interest in our project !

Pushdown of an aggregate operator is only allowed if all filters are able to be pushed down successfully.  This is a part of the Spark [V2ScanRelationPushdown ](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/V2ScanRelationPushDown.scala) rule too.  It is essential that all filters be applied since the aggregate operation applied to non-filtered data would produce the wrong aggregate result.

For our pushdown capable datasource we make a best effort to perform the enabled pushdowns for a given query.  But if a class of pushdowns are not possible for the query then we will proceed without that class of pushdown.  Filter is the best example, and if filters cannot all be pushed, we will proceed without filter pushdown, but will still include the projects (column pruning).  Similarly if certain aggregate operations could not be pushed, we could still proceed with valid filters and projects (column pruning).

Best Regards,
Rob

**Comment by emanuel1025** [comment]
Thanks, that answered our questions!
